# Generated by Django 5.2.17 on 2026-09-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forumpost_liked_by_forumtopic_is_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('type_label', models.CharField(blank=True, max_length=200)),
                ('accreditation_status', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='accreditations/certificates/')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='core.accreditation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('beneficiaries', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('services', models.TextField(help_text='One service per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.accreditation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AccreditationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.accreditation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
