# Generated by Django 4.2.7 on 2026-05-24 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_forumpost_forumtopic_remove_discussionreply_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('opportunity_type', models.CharField(choices=[('learnership', 'Learnership'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('job', 'Job Vacancy'), ('funding', 'Funding Opportunity'), ('bursary', 'Bursary'), ('training', 'Training Programme')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='List requirements, one per line or use bullet points')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities for the role')),
                ('location', models.CharField(max_length=200)),
                ('remote_options', models.BooleanField(default=False)),
                ('stipend_amount', models.CharField(blank=True, help_text='e.g., R3500 per month', max_length=100)),
                ('funding_amount', models.CharField(blank=True, help_text='e.g., Up to R100,000', max_length=100)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('available_positions', models.IntegerField(default=1)),
                ('positions_filled', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority in listings')),
                ('contact_email', models.EmailField(default='careers@malitinne.co.za', max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('application_instructions', models.TextField(blank=True, help_text='Special instructions for applying')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('race', models.CharField(blank=True, choices=[('african', 'African'), ('coloured', 'Coloured'), ('indian', 'Indian'), ('white', 'White'), ('other', 'Other')], help_text='For BBBEE/Employment Equity purposes', max_length=50)),
                ('disability', models.CharField(blank=True, help_text='Specify disability if applicable', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('EC', 'Eastern Cape'), ('FS', 'Free State'), ('GP', 'Gauteng'), ('KZN', 'KwaZulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('highest_qualification', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year_completed', models.IntegerField()),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('work_experience', models.TextField(blank=True, help_text='Previous work experience')),
                ('skills', models.TextField(help_text='Relevant skills, separated by commas')),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cvs/%Y/%m/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='applications/cover_letters/%Y/%m/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='applications/ids/%Y/%m/')),
                ('qualifications', models.FileField(blank=True, null=True, upload_to='applications/qualifications/%Y/%m/')),
                ('hear_about_us', models.CharField(blank=True, help_text='How did you hear about this opportunity?', max_length=200)),
                ('additional_info', models.TextField(blank=True, help_text="Any additional information you'd like to share")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Stage'), ('assessment', 'Assessment Stage'), ('offered', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Internal notes about application status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Application score out of 100', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.opportunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
